
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.mca]
		enable_compat_mca = true

	[Compatibility.jade]
		enable_compat_jade = true

